### ISSUE TITLE
Windows Notification Spam

### ISSUE THREAD

**Issue by Hanomalous** [FSpark/Danbooru-Tags-Exporter#12]
whenever I have this scrip activated I get windows notification boxes every couple minutes even when I'm not using the script.

Browser: Firefox

**Comment by FSpark** [comment]
What kind of windows notification is it? Please post a screenshot. I also use Firefox and have never encountered this situation.

**Comment by Hanomalous** [comment]
> What kind of windows notification is it?

![OT1rMPokEn](https://github.com/FSpark/Danbooru-Tags-Exporter/assets/165978082/3ed5b981-d10c-4fbf-a352-d433ced47df6)

I'm unable to reproduce it now, It just stopped happening after restarting my pc. Most probably an issue unrelated to this script.  

sorry for the inconvenience
