### ISSUE TITLE
Doesn't work with Greasemonkey (Firefox)

### ISSUE THREAD

**Issue by Meladoom2** [FSpark/Danbooru-Tags-Exporter#4]
Turning every addon off doesn't help.
Script Version - 0.3.1
Firefox Version - 115.0.2
Greasemonkey Version - 4.11

Just tried this out on Microsoft Edge with Tampermonkey and it worked. So I assume there's something related to Greasemonkey

**Comment by FSpark** [comment]
Thanks for your feedback, because `GM_addStyle` has been [removed](https://wiki.greasespot.net/GM_addStyle "GM addStyle - GreaseSpot Wiki") in GM4, it has been fixed, please test it.

**Comment by Meladoom2** [comment]
Yes, it works, the buttons have appeared, but now when I press "Export" nothing happens.
I just tried to Export tags from Edge (Tampermonkey), and got a notification (Windows 10) that they were copied to the Clipboard, and it works. But not in Firefox (Greasemonkey).

All other addons were turned off
